INSERT INTO domain (name) VALUES("00 - Kommunens styrelse");
INSERT INTO domain (name) VALUES("01 - Fysisk planlægning og naturbeskyttelse");
INSERT INTO domain (name) VALUES("02 - Byggeri");
INSERT INTO domain (name) VALUES("03 - Boliger");
INSERT INTO domain (name) VALUES("04 - Parker, fritids-/idrætsanlæg og landskabspleje mv.");
INSERT INTO domain (name) VALUES("05 - Veje og trafik");
INSERT INTO domain (name) VALUES("06 - Spildevand og vandløb");
INSERT INTO domain (name) VALUES("07 - Affald og genanvendelse");
INSERT INTO domain (name) VALUES("08 - Havne og lufthavne");
INSERT INTO domain (name) VALUES("09 - Miljøbeskyttelse");
INSERT INTO domain (name) VALUES("13 - Forsyning");
INSERT INTO domain (name) VALUES("14 - Beredskab");
INSERT INTO domain (name) VALUES("15 - Arbejdsmarked og beskæftigelsesindsats");
INSERT INTO domain (name) VALUES("17 - Folkeskoleundervisning");
INSERT INTO domain (name) VALUES("18 - Folkeoplysning og ungdomsskoler");
INSERT INTO domain (name) VALUES("19 - Kulturhistoriske institutioner");
INSERT INTO domain (name) VALUES("20 - Kulturvirksomhed");
INSERT INTO domain (name) VALUES("21 - Biblioteker");
INSERT INTO domain (name) VALUES("22 - Regulering af private erhverv");
INSERT INTO domain (name) VALUES("23 - Borgerlige forhold");
INSERT INTO domain (name) VALUES("24 - Erhvervsforhold");
INSERT INTO domain (name) VALUES("25 - Beskatning");
INSERT INTO domain (name) VALUES("27 - Social service");
INSERT INTO domain (name) VALUES("28 - Dagtilbud");
INSERT INTO domain (name) VALUES("29 - Sundhed");
INSERT INTO domain (name) VALUES("30 - Andre myndigheders opgaver");
INSERT INTO domain (name) VALUES("32 - Kontante ydelser");
INSERT INTO domain (name) VALUES("54 - Uddannelse");
INSERT INTO domain (name) VALUES("81 - Kommunens personale");
INSERT INTO domain (name) VALUES("82 - Kommunens ejendomme og lokaler");
INSERT INTO domain (name) VALUES("83 - Kommunens driftsmidler og inventar");
INSERT INTO domain (name) VALUES("84 - Offentlige valg");
INSERT INTO domain (name) VALUES("85 - Kommunens administrative systemer");
INSERT INTO domain (name) VALUES("86 - Kommunens selvforsyning og fremstillingsvirksomhed");
INSERT INTO domain (name) VALUES("87 - Kommunens arbejdsmiljø");
INSERT INTO domain (name) VALUES("88 - Kommunens indkøb og udbud");
